#! /bin/bash

# waits until hadoop is ready
while ! systemctl is-active --quiet hadoop-yarn-resourcemanager ; do 
  echo "Yarn Resource Manager is not active, will retry in 10 seconds"
  sleep 10
done

yarn rmadmin -removeFromClusterNodeLabels "CORE"
yarn rmadmin -addToClusterNodeLabels "TASK(exclusive=false)"
yarn rmadmin -addToClusterNodeLabels "CORE(exclusive=true)"
./cloudgene server

